// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:amap_map_fluttify/src/android/android.export.g.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';
import 'package:amap_location_fluttify/amap_location_fluttify.dart';
import 'package:amap_search_fluttify/amap_search_fluttify.dart';
import 'package:url_launcher/url_launcher.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
// type check
@optionalTypeArgs
Future<bool> AmapMapFluttifyAndroidIs<T>(dynamic __this__) async {
  final typeName = T.toString();
  if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ is T;
  }
  else if (T == com_amap_api_offlineservice_AMapPermissionActivity) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_offlineservice_AMapPermissionActivity', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_UiSettings) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_UiSettings', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_SwipeDismissTouchListener) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_SwipeDismissTouchListener', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_InfoWindowParams) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_InfoWindowParams', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_CameraUpdateFactory) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_CameraUpdateFactory', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMapException) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMapException', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMapOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMapOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_CoordinateConverter) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_CoordinateConverter', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMap_InfoWindowAdapter) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMap_InfoWindowAdapter', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMap_ImageInfoWindowAdapter) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMap_ImageInfoWindowAdapter', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_utils_SpatialRelationUtil) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_utils_SpatialRelationUtil', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_utils_overlay_MovingPointOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_utils_overlay_MovingPointOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_utils_overlay_SmoothMoveMarker) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_utils_overlay_SmoothMoveMarker', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_CameraUpdate) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_CameraUpdate', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_SwipeDismissCallBack) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_SwipeDismissCallBack', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_SwipeDismissView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_SwipeDismissView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_MapsInitializer) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_MapsInitializer', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapStatus) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_OfflineMapStatus', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapProvince) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_OfflineMapProvince', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_DownloadProgressView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_DownloadProgressView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_Province) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_Province', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapManager) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_OfflineMapManager', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapCity) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_OfflineMapCity', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapActivity) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_OfflineMapActivity', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_offlinemap_City) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_offlinemap_City', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_Projection) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_Projection', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMap_MultiPositionInfoWindowAdapter) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMap_MultiPositionInfoWindowAdapter', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Polygon) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Polygon', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_HeatMapLayerOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_HeatMapLayerOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BitmapDescriptor) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BitmapDescriptor', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_PolygonHoleOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_PolygonHoleOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Poi) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Poi', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MyLocationStyle) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MyLocationStyle', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_RouteOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_RouteOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_VisibleRegion) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_VisibleRegion', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CircleHoleOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CircleHoleOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Text) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Text', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_LatLngBounds_Builder) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_LatLngBounds_Builder', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_HeatMapLayer) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_HeatMapLayer', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_NavigateArrowOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_NavigateArrowOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BitmapDescriptorFactory) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BitmapDescriptorFactory', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_UrlTileProvider) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_UrlTileProvider', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MultiPointOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MultiPointOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_PolylineOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_PolylineOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Tile) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Tile', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_GL3DModel) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_GL3DModel', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Gradient) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Gradient', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_TileProvider) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_TileProvider', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_HeatMapItem) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_HeatMapItem', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_NaviPara) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_NaviPara', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_GroundOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_GroundOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_GL3DModelOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_GL3DModelOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_GroundOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_GroundOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MyTrafficStyle) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MyTrafficStyle', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CameraPosition) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CameraPosition', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_PoiPara) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_PoiPara', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MarkerOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MarkerOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_HeatmapTileProvider) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_HeatmapTileProvider', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_NavigateArrow) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_NavigateArrow', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_AnimationSet) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_AnimationSet', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_RotateAnimation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_RotateAnimation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_TranslateAnimation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_TranslateAnimation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_Animation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_Animation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_EmergeAnimation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_EmergeAnimation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_AlphaAnimation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_AlphaAnimation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_animation_ScaleAnimation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_animation_ScaleAnimation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_LatLngBounds) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_LatLngBounds', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CustomMapStyleOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CustomMapStyleOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BuildingOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BuildingOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CrossOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CrossOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_LatLng) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_LatLng', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_TileProjection) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_TileProjection', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_AMapPara) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_AMapPara', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CameraPosition_Builder) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CameraPosition_Builder', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BasePointOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BasePointOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Arc) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Arc', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_AMapCameraInfo) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_AMapCameraInfo', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Circle) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Circle', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_PolygonOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_PolygonOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_WeightedLatLng) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_WeightedLatLng', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MultiPointItem) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MultiPointItem', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_ArcOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_ArcOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CircleOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CircleOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_RuntimeRemoteException) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_RuntimeRemoteException', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_AMapGLOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_AMapGLOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_HeatmapTileProvider_Builder) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_HeatmapTileProvider_Builder', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_MultiPointOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_MultiPointOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BaseOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BaseOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BaseOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BaseOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Marker) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Marker', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_TileOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_TileOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_RoutePara) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_RoutePara', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_CrossOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_CrossOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlayOptionsFactory) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_particle_ParticleOverlayOptionsFactory', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlayOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_particle_ParticleOverlayOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_particle_ParticleOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BaseHoleOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BaseHoleOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_TextOptions) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_TextOptions', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_TileOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_TileOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_IndoorBuildingInfo) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_IndoorBuildingInfo', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_Polyline) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_Polyline', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_model_BuildingOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_model_BuildingOverlay', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_SwipeDismissTouchListener_DismissCallbacks) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_SwipeDismissTouchListener_DismissCallbacks', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_TextureMapView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_TextureMapView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMapUtils) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMapUtils', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_InfoWindowAnimationManager) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_InfoWindowAnimationManager', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_WearMapView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_WearMapView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_BaseMapView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_BaseMapView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_AMap) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_AMap', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_maps_MapView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_maps_MapView', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_trace_TraceLocation) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_trace_TraceLocation', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_trace_LBSTraceClient) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_trace_LBSTraceClient', {'__this__': __this__});
    return result;
  } else if (T == com_amap_api_trace_TraceOverlay) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfcom_amap_api_trace_TraceOverlay', {'__this__': __this__});
    return result;
  } else if (T == android_content_Context) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_Context', {'__this__': __this__});
    return result;
  } else if (T == android_content_Intent) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_Intent', {'__this__': __this__});
    return result;
  } else if (T == android_content_ContentProvider) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_content_ContentProvider', {'__this__': __this__});
    return result;
  } else if (T == android_app_Application) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Application', {'__this__': __this__});
    return result;
  } else if (T == android_app_Notification) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Notification', {'__this__': __this__});
    return result;
  } else if (T == android_app_Activity) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_Activity', {'__this__': __this__});
    return result;
  } else if (T == android_app_PendingIntent) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_app_PendingIntent', {'__this__': __this__});
    return result;
  } else if (T == android_os_Bundle) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Bundle', {'__this__': __this__});
    return result;
  } else if (T == android_os_Binder) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Binder', {'__this__': __this__});
    return result;
  } else if (T == android_view_View) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_View', {'__this__': __this__});
    return result;
  } else if (T == android_view_SurfaceView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_SurfaceView', {'__this__': __this__});
    return result;
  } else if (T == android_view_ViewGroup) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_ViewGroup', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_Point) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_Point', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_PointF) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_PointF', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_Bitmap) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_Bitmap', {'__this__': __this__});
    return result;
  } else if (T == android_widget_ImageView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_ImageView', {'__this__': __this__});
    return result;
  } else if (T == java_io_File) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfjava_io_File', {'__this__': __this__});
    return result;
  } else if (T == android_location_Location) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_location_Location', {'__this__': __this__});
    return result;
  } else if (T == android_view_MotionEvent) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_view_MotionEvent', {'__this__': __this__});
    return result;
  } else if (T == android_graphics_drawable_Drawable) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_graphics_drawable_Drawable', {'__this__': __this__});
    return result;
  } else if (T == android_widget_FrameLayout) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_FrameLayout', {'__this__': __this__});
    return result;
  } else if (T == android_widget_TextView) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_TextView', {'__this__': __this__});
    return result;
  } else if (T == android_widget_LinearLayout) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_LinearLayout', {'__this__': __this__});
    return result;
  } else if (T == android_widget_RelativeLayout) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_widget_RelativeLayout', {'__this__': __this__});
    return result;
  } else if (T == android_os_Parcelable) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_os_Parcelable', {'__this__': __this__});
    return result;
  } else if (T == android_util_Pair) {
    final result = await kAmapMapFluttifyChannel.invokeMethod('RefClass::isKindOfandroid_util_Pair', {'__this__': __this__});
    return result;
  }
  else {
    return false;
  }
}

// type cast
// 给一个可选的泛型, 如果没有指定泛型就返回dynamic
@optionalTypeArgs
T AmapMapFluttifyAndroidAs<T>(dynamic __this__) {
  final typeName = T.toString();

  if (__this__ == null) {
    return null;
  } else if (RegExp(r'^(List<)?(String|int|double)(>)?|(Map<String,(String|int|double)>)$').hasMatch(typeName)) {
    return __this__ as T;
  }
  else if (T == com_amap_api_offlineservice_AMapPermissionActivity) {
    return (com_amap_api_offlineservice_AMapPermissionActivity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_UiSettings) {
    return (com_amap_api_maps_UiSettings()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_SwipeDismissTouchListener) {
    return (com_amap_api_maps_SwipeDismissTouchListener()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_InfoWindowParams) {
    return (com_amap_api_maps_InfoWindowParams()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_CameraUpdateFactory) {
    return (com_amap_api_maps_CameraUpdateFactory()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMapException) {
    return (com_amap_api_maps_AMapException()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMapOptions) {
    return (com_amap_api_maps_AMapOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_CoordinateConverter) {
    return (com_amap_api_maps_CoordinateConverter()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMap_InfoWindowAdapter) {
    return (com_amap_api_maps_AMap_InfoWindowAdapter.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMap_ImageInfoWindowAdapter) {
    return (com_amap_api_maps_AMap_ImageInfoWindowAdapter.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_utils_SpatialRelationUtil) {
    return (com_amap_api_maps_utils_SpatialRelationUtil()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_utils_overlay_MovingPointOverlay) {
    return (com_amap_api_maps_utils_overlay_MovingPointOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_utils_overlay_SmoothMoveMarker) {
    return (com_amap_api_maps_utils_overlay_SmoothMoveMarker()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_CameraUpdate) {
    return (com_amap_api_maps_CameraUpdate()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_SwipeDismissCallBack) {
    return (com_amap_api_maps_SwipeDismissCallBack()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_SwipeDismissView) {
    return (com_amap_api_maps_SwipeDismissView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_MapsInitializer) {
    return (com_amap_api_maps_MapsInitializer()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapStatus) {
    return (com_amap_api_maps_offlinemap_OfflineMapStatus()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapProvince) {
    return (com_amap_api_maps_offlinemap_OfflineMapProvince()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_DownloadProgressView) {
    return (com_amap_api_maps_offlinemap_DownloadProgressView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_Province) {
    return (com_amap_api_maps_offlinemap_Province()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapManager) {
    return (com_amap_api_maps_offlinemap_OfflineMapManager()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapCity) {
    return (com_amap_api_maps_offlinemap_OfflineMapCity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_OfflineMapActivity) {
    return (com_amap_api_maps_offlinemap_OfflineMapActivity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_offlinemap_City) {
    return (com_amap_api_maps_offlinemap_City()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_Projection) {
    return (com_amap_api_maps_Projection()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMap_MultiPositionInfoWindowAdapter) {
    return (com_amap_api_maps_AMap_MultiPositionInfoWindowAdapter.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Polygon) {
    return (com_amap_api_maps_model_Polygon()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_HeatMapLayerOptions) {
    return (com_amap_api_maps_model_HeatMapLayerOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BitmapDescriptor) {
    return (com_amap_api_maps_model_BitmapDescriptor()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_PolygonHoleOptions) {
    return (com_amap_api_maps_model_PolygonHoleOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Poi) {
    return (com_amap_api_maps_model_Poi()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MyLocationStyle) {
    return (com_amap_api_maps_model_MyLocationStyle()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_RouteOverlay) {
    return (com_amap_api_maps_model_RouteOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_VisibleRegion) {
    return (com_amap_api_maps_model_VisibleRegion()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CircleHoleOptions) {
    return (com_amap_api_maps_model_CircleHoleOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Text) {
    return (com_amap_api_maps_model_Text()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_LatLngBounds_Builder) {
    return (com_amap_api_maps_model_LatLngBounds_Builder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_HeatMapLayer) {
    return (com_amap_api_maps_model_HeatMapLayer()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_NavigateArrowOptions) {
    return (com_amap_api_maps_model_NavigateArrowOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BitmapDescriptorFactory) {
    return (com_amap_api_maps_model_BitmapDescriptorFactory()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_UrlTileProvider) {
    return (com_amap_api_maps_model_UrlTileProvider()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MultiPointOverlayOptions) {
    return (com_amap_api_maps_model_MultiPointOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_PolylineOptions) {
    return (com_amap_api_maps_model_PolylineOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Tile) {
    return (com_amap_api_maps_model_Tile()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_GL3DModel) {
    return (com_amap_api_maps_model_GL3DModel()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Gradient) {
    return (com_amap_api_maps_model_Gradient()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_TileProvider) {
    return (com_amap_api_maps_model_TileProvider.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_HeatMapItem) {
    return (com_amap_api_maps_model_HeatMapItem()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_NaviPara) {
    return (com_amap_api_maps_model_NaviPara()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_GroundOverlayOptions) {
    return (com_amap_api_maps_model_GroundOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_GL3DModelOptions) {
    return (com_amap_api_maps_model_GL3DModelOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_GroundOverlay) {
    return (com_amap_api_maps_model_GroundOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MyTrafficStyle) {
    return (com_amap_api_maps_model_MyTrafficStyle()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CameraPosition) {
    return (com_amap_api_maps_model_CameraPosition()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_PoiPara) {
    return (com_amap_api_maps_model_PoiPara()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MarkerOptions) {
    return (com_amap_api_maps_model_MarkerOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_HeatmapTileProvider) {
    return (com_amap_api_maps_model_HeatmapTileProvider()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_NavigateArrow) {
    return (com_amap_api_maps_model_NavigateArrow()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_AnimationSet) {
    return (com_amap_api_maps_model_animation_AnimationSet()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_RotateAnimation) {
    return (com_amap_api_maps_model_animation_RotateAnimation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_TranslateAnimation) {
    return (com_amap_api_maps_model_animation_TranslateAnimation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_Animation) {
    return (com_amap_api_maps_model_animation_Animation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_EmergeAnimation) {
    return (com_amap_api_maps_model_animation_EmergeAnimation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_AlphaAnimation) {
    return (com_amap_api_maps_model_animation_AlphaAnimation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_animation_ScaleAnimation) {
    return (com_amap_api_maps_model_animation_ScaleAnimation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_LatLngBounds) {
    return (com_amap_api_maps_model_LatLngBounds()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CustomMapStyleOptions) {
    return (com_amap_api_maps_model_CustomMapStyleOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BuildingOverlayOptions) {
    return (com_amap_api_maps_model_BuildingOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CrossOverlayOptions) {
    return (com_amap_api_maps_model_CrossOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_LatLng) {
    return (com_amap_api_maps_model_LatLng()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_TileProjection) {
    return (com_amap_api_maps_model_TileProjection()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_AMapPara) {
    return (com_amap_api_maps_model_AMapPara()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CameraPosition_Builder) {
    return (com_amap_api_maps_model_CameraPosition_Builder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BasePointOverlay) {
    return (com_amap_api_maps_model_BasePointOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Arc) {
    return (com_amap_api_maps_model_Arc()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_AMapCameraInfo) {
    return (com_amap_api_maps_model_AMapCameraInfo()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Circle) {
    return (com_amap_api_maps_model_Circle()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_PolygonOptions) {
    return (com_amap_api_maps_model_PolygonOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_WeightedLatLng) {
    return (com_amap_api_maps_model_WeightedLatLng()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MultiPointItem) {
    return (com_amap_api_maps_model_MultiPointItem()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_ArcOptions) {
    return (com_amap_api_maps_model_ArcOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CircleOptions) {
    return (com_amap_api_maps_model_CircleOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_RuntimeRemoteException) {
    return (com_amap_api_maps_model_RuntimeRemoteException()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_AMapGLOverlay) {
    return (com_amap_api_maps_model_AMapGLOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_HeatmapTileProvider_Builder) {
    return (com_amap_api_maps_model_HeatmapTileProvider_Builder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_MultiPointOverlay) {
    return (com_amap_api_maps_model_MultiPointOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BaseOptions) {
    return (com_amap_api_maps_model_BaseOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BaseOverlay) {
    return (com_amap_api_maps_model_BaseOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Marker) {
    return (com_amap_api_maps_model_Marker()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_TileOverlayOptions) {
    return (com_amap_api_maps_model_TileOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_RoutePara) {
    return (com_amap_api_maps_model_RoutePara()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_CrossOverlay) {
    return (com_amap_api_maps_model_CrossOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlayOptionsFactory) {
    return (com_amap_api_maps_model_particle_ParticleOverlayOptionsFactory()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlayOptions) {
    return (com_amap_api_maps_model_particle_ParticleOverlayOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_particle_ParticleOverlay) {
    return (com_amap_api_maps_model_particle_ParticleOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BaseHoleOptions) {
    return (com_amap_api_maps_model_BaseHoleOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_TextOptions) {
    return (com_amap_api_maps_model_TextOptions()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_TileOverlay) {
    return (com_amap_api_maps_model_TileOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_IndoorBuildingInfo) {
    return (com_amap_api_maps_model_IndoorBuildingInfo()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_Polyline) {
    return (com_amap_api_maps_model_Polyline()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_model_BuildingOverlay) {
    return (com_amap_api_maps_model_BuildingOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_SwipeDismissTouchListener_DismissCallbacks) {
    return (com_amap_api_maps_SwipeDismissTouchListener_DismissCallbacks.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_TextureMapView) {
    return (com_amap_api_maps_TextureMapView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMapUtils) {
    return (com_amap_api_maps_AMapUtils()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_InfoWindowAnimationManager) {
    return (com_amap_api_maps_InfoWindowAnimationManager()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_WearMapView) {
    return (com_amap_api_maps_WearMapView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_BaseMapView) {
    return (com_amap_api_maps_BaseMapView.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_AMap) {
    return (com_amap_api_maps_AMap()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_maps_MapView) {
    return (com_amap_api_maps_MapView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_trace_TraceLocation) {
    return (com_amap_api_trace_TraceLocation()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_trace_LBSTraceClient) {
    return (com_amap_api_trace_LBSTraceClient()..refId = (__this__ as Ref).refId) as T;
  } else if (T == com_amap_api_trace_TraceOverlay) {
    return (com_amap_api_trace_TraceOverlay()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_Context) {
    return (android_content_Context()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_Intent) {
    return (android_content_Intent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_content_ContentProvider) {
    return (android_content_ContentProvider()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Application) {
    return (android_app_Application()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Notification) {
    return (android_app_Notification()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_Activity) {
    return (android_app_Activity()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_app_PendingIntent) {
    return (android_app_PendingIntent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Bundle) {
    return (android_os_Bundle()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Binder) {
    return (android_os_Binder()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_View) {
    return (android_view_View()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_SurfaceView) {
    return (android_view_SurfaceView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_ViewGroup) {
    return (android_view_ViewGroup()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_Point) {
    return (android_graphics_Point()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_PointF) {
    return (android_graphics_PointF()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_Bitmap) {
    return (android_graphics_Bitmap()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_ImageView) {
    return (android_widget_ImageView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == java_io_File) {
    return (java_io_File()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_location_Location) {
    return (android_location_Location()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_view_MotionEvent) {
    return (android_view_MotionEvent()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_graphics_drawable_Drawable) {
    return (android_graphics_drawable_Drawable()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_FrameLayout) {
    return (android_widget_FrameLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_TextView) {
    return (android_widget_TextView()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_LinearLayout) {
    return (android_widget_LinearLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_widget_RelativeLayout) {
    return (android_widget_RelativeLayout()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_os_Parcelable) {
    return (android_os_Parcelable.subInstance()..refId = (__this__ as Ref).refId) as T;
  } else if (T == android_util_Pair) {
    return (android_util_Pair()..refId = (__this__ as Ref).refId) as T;
  }
  else if (AmapCoreFluttifyAndroidAs<T>(__this__) != null) {
    return AmapCoreFluttifyAndroidAs<T>(__this__);
  } else if (AmapLocationFluttifyAndroidAs<T>(__this__) != null) {
    return AmapLocationFluttifyAndroidAs<T>(__this__);
  } else if (AmapSearchFluttifyAndroidAs<T>(__this__) != null) {
    return AmapSearchFluttifyAndroidAs<T>(__this__);
  }
  else {
    return null;
  }
}