// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////
import 'package:flutter/services.dart';
import '../facade/objects.g.dart';

Future<String> get MAOfflineMapErrorDomain async {
  return kAmapMapFluttifyChannel.invokeMethod('getMAOfflineMapErrorDomain');
}

Future<String> get MAOfflineMapDownloadReceivedSizeKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getMAOfflineMapDownloadReceivedSizeKey');
}

Future<String> get MAOfflineMapDownloadExpectedSizeKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getMAOfflineMapDownloadExpectedSizeKey');
}

Future<String> get kMAMapLayerCenterMapPointKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getkMAMapLayerCenterMapPointKey');
}

Future<String> get kMAMapLayerZoomLevelKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getkMAMapLayerZoomLevelKey');
}

Future<String> get kMAMapLayerRotationDegreeKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getkMAMapLayerRotationDegreeKey');
}

Future<String> get kMAMapLayerCameraDegreeKey async {
  return kAmapMapFluttifyChannel.invokeMethod('getkMAMapLayerCameraDegreeKey');
}
