// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_map_fluttify/src/ios/ios.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';

class MAMultiTexturePolylineRenderer extends MAPolylineRenderer  {
  //region constants
  static const String name__ = 'MAMultiTexturePolylineRenderer';

  @override
  final String tag__ = 'amap_map_fluttify';

  
  //endregion

  //region creators
  static Future<MAMultiTexturePolylineRenderer> create__({ bool init = true /* ios only */ }) async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod(
      'ObjectFactory::createMAMultiTexturePolylineRenderer',
      {'init': init}
    );
    return AmapMapFluttifyIOSAs<MAMultiTexturePolylineRenderer>(__result__);
  }
  
  static Future<List<MAMultiTexturePolylineRenderer>> create_batch__(int length, { bool init = true /* ios only */ }) async {
    assert(true);
    final __result_batch__ = await  kAmapMapFluttifyChannel.invokeListMethod(
      'ObjectFactory::create_batchMAMultiTexturePolylineRenderer',
      {'length': length, 'init': init}
    );
    return __result_batch__
        .map((it) => AmapMapFluttifyIOSAs<MAMultiTexturePolylineRenderer>(it))
        .toList();
  }
  
  //endregion

  //region getters
  Future<MAMultiPolyline> get_multiPolyline() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_multiPolyline", {'__this__': this});
    return AmapMapFluttifyIOSAs<MAMultiPolyline>(__result__);
  }
  
  Future<List<dynamic>> get_strokeTextureImages() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_strokeTextureImages", {'__this__': this});
    return (__result__ as List).cast<dynamic>();
  }
  
  Future<List<num>> get_strokeTextureIDs() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_strokeTextureIDs", {'__this__': this});
    return (__result__ as List).cast<num>();
  }
  
  Future<bool> get_showRangeEnabled() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_showRangeEnabled", {'__this__': this});
    return __result__;
  }
  
  Future<MAPathShowRange> get_showRange() async {
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_showRange", {'__this__': this});
    return AmapMapFluttifyIOSAs<MAPathShowRange>(__result__);
  }
  
  //endregion

  //region setters
  Future<void> set_strokeTextureImages(List<dynamic> strokeTextureImages) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_strokeTextureImages', <String, dynamic>{'__this__': this, "strokeTextureImages": strokeTextureImages});
  
  
  }
  
  Future<void> set_showRangeEnabled(bool showRangeEnabled) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_showRangeEnabled', <String, dynamic>{'__this__': this, "showRangeEnabled": showRangeEnabled});
  
  
  }
  
  Future<void> set_showRange(MAPathShowRange showRange) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_showRange', <String, dynamic>{'__this__': this, "showRange": showRange});
  
  
  }
  
  //endregion

  //region methods
  
  Future<MAMultiTexturePolylineRenderer> initWithMultiPolyline(MAMultiPolyline multiPolyline) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: MAMultiTexturePolylineRenderer@$refId::initWithMultiPolyline([])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::initWithMultiPolyline', {"multiPolyline": multiPolyline, "__this__": this});
  
  
    // handle native call
  
  
    return AmapMapFluttifyIOSAs<MAMultiTexturePolylineRenderer>(__result__);
  }
  
  @deprecated
  Future<bool> loadStrokeTextureImages(List<dynamic> textureImages) async {
    // print log
    if (fluttifyLogEnabled) {
      debugPrint('fluttify-dart: MAMultiTexturePolylineRenderer@$refId::loadStrokeTextureImages([])');
    }
  
    // invoke native method
    final __result__ = await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::loadStrokeTextureImages', {"textureImages": textureImages, "__this__": this});
  
  
    // handle native call
  
  
    return __result__;
  }
  
  //endregion

  @override
  String toString() {
    return 'MAMultiTexturePolylineRenderer{refId: $refId, runtimeType: $runtimeType, tag__: $tag__}';
  }
}

extension MAMultiTexturePolylineRenderer_Batch on List<MAMultiTexturePolylineRenderer> {
  //region getters
  Future<List<MAMultiPolyline>> get_multiPolyline_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_multiPolyline_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => AmapMapFluttifyIOSAs<MAMultiPolyline>(__result__))?.cast<MAMultiPolyline>()?.toList();
  }
  
  Future<List<List<dynamic>>> get_strokeTextureImages_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_strokeTextureImages_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => (__result__ as List).cast<dynamic>())?.cast<List<dynamic>>()?.toList();
  }
  
  Future<List<List<num>>> get_strokeTextureIDs_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_strokeTextureIDs_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => (__result__ as List).cast<num>())?.cast<List<num>>()?.toList();
  }
  
  Future<List<bool>> get_showRangeEnabled_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_showRangeEnabled_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => __result__)?.cast<bool>()?.toList();
  }
  
  Future<List<MAPathShowRange>> get_showRange_batch() async {
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod("MAMultiTexturePolylineRenderer::get_showRange_batch", [for (final __item__ in this) {'__this__': __item__}]);
    return (resultBatch as List)?.map((__result__) => AmapMapFluttifyIOSAs<MAPathShowRange>(__result__))?.cast<MAPathShowRange>()?.toList();
  }
  
  //endregion

  //region setters
  Future<void> set_strokeTextureImages_batch(List<List<dynamic>> strokeTextureImages) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_strokeTextureImages_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "strokeTextureImages": strokeTextureImages[__i__]}]);
  
  
  }
  
  Future<void> set_showRangeEnabled_batch(List<bool> showRangeEnabled) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_showRangeEnabled_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "showRangeEnabled": showRangeEnabled[__i__]}]);
  
  
  }
  
  Future<void> set_showRange_batch(List<MAPathShowRange> showRange) async {
    await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::set_showRange_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {'__this__': this[__i__], "showRange": showRange[__i__]}]);
  
  
  }
  
  //endregion

  //region methods
  
  Future<List<MAMultiTexturePolylineRenderer>> initWithMultiPolyline_batch(List<MAMultiPolyline> multiPolyline) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::initWithMultiPolyline_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"multiPolyline": multiPolyline[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => AmapMapFluttifyIOSAs<MAMultiTexturePolylineRenderer>(__result__)).cast<MAMultiTexturePolylineRenderer>().toList();
  }
  
  @deprecated
  Future<List<bool>> loadStrokeTextureImages_batch(List<List<dynamic>> textureImages) async {
    assert(true);
  
    // invoke native method
    final resultBatch = await kAmapMapFluttifyChannel.invokeMethod('MAMultiTexturePolylineRenderer::loadStrokeTextureImages_batch', [for (int __i__ = 0; __i__ < this.length; __i__++) {"textureImages": textureImages[__i__], "__this__": this[__i__]}]);
  
  
    return (resultBatch as List).map((__result__) => __result__).cast<bool>().toList();
  }
  
  //endregion
}